version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: ${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
